### PR TITLE
fix: code changes to prevent editing teams to have same type and id

### LINKED ISSUE #1381: Newly created team not visible immediately and no success toaster message displayed
### Is there an existing issue for this?

- [x] I confirm that I have not found an existing or similar issue.

### How to reproduce the issue

1.Login to the application.
2.Navigate to setting and enable admin mode
3.Navigate to Team Permission page.
4.Click on Add Team button.
4.Enter valid team details and click on ADD button
5.Observe the toaster message confirmation.
6.Check the team list.

### Expected Result

- A success toaster message should be displayed after creating a team.
- The newly created team should be visible in the team list immediately without requiring a page refresh.

### Actual Results

-No success toaster message is displayed.
-The team is only visible after manually refreshing the page.

### Additional Context

Image

### Requirements or Tasks

_No response_

### Have you reproduced the issue with at least the latest released version?

- [x] Yes

### I have checked my terminal/console and have included relevant text here?

- [x] Yes

### LINKED ISSUE #1520: [TASK] Style "Edit Team" Modal
Current Modal: 
Image

Link to Modal on Figma: https://www.figma.com/design/9gIqLnOoJuVQZCDPOrplXa/Member---Team-Permissions?node-id=1539-38420&m=dev

Everything content wise is there, but it's not 1-1 with the Figma. Biggest difference is that the Description input on Figma is a textfield that expands vertically rather than scrolling horizontally, but should check general styling as well (i.e. input field sizes, they appear to not be as big height-wise on the figma, and the action buttons are off)

^^ Double check with the Figma for more specific styling to get it closer to be 1-1 with the Figma, these are just the things that are glaringly different

### PR DESCRIPTION
**Pull request by Subhadeepghosh1**
Description
Prevent editing teams to already existing type and groupId.

Changes Made
Added groupExists check logic before trying to edit group.

How to Test
1. Go to the setting page
2. Go to the team permission page
3. Try to edit a existing team.
4. Upon adding already existing groupId and Type it throws error.

### CODE REVIEW

File: src/prerna/auth/utils/AdminSecurityGroupUtils.java [hunk 1]
```diff
@@ -220,7 +220,6 @@ public void deleteGroupAndPropagate(String groupId, String groupType) throws Exc
 	 * @param newGroupId
 	 * @param newGroupType
 	 * @param newDescription
-	 * @param newIsCustomGroup
 	 * @throws Exception
 	 */
 	public void editGroupAndPropagate(User user, String curGroupId, String curGroupType, String newGroupId,
```
Comment (anurag91jain) [inline src/prerna/auth/utils/AdminSecurityGroupUtils.java:215]: what's the difference between this function and editGroupDetailsAndPropagate

File: src/prerna/auth/utils/AdminSecurityGroupUtils.java [hunk 2]
```diff
@@ -363,19 +299,21 @@ public void editGroupDetailsAndPropagate(User user, String curGroupId, String cu
 	 * @param newGroupId
 	 * @param newGroupType
 	 * @param newDescription
-	 * @param newIsCustomGroup
 	 * @throws Exception
 	 */
 	public void editGroupDetailsAndPropagate(User user, String curGroupId, String curGroupType, String newGroupId,
-			String newGroupType, String newDescription, boolean newIsCustomGroup) throws Exception {
```
Comment (anurag91jain) [inline src/prerna/auth/utils/AdminSecurityGroupUtils.java:370]: there will not be anything such as newgrouptype. grouptype should not be editable. @themaherkhalil  @kunal0137

**Review by anurag91jain — DISMISSED** [review]
