### PR TITLE
733 vectordatabasequeryreactor output divider value for word doc chunks always 1

### LINKED ISSUE #733: [BE] VectorDatabaseQueryReactor output: "Divider" value for word doc chunks always "1"
### A clear and concise description of what the issue is.
The VectorDatabaseQueryReactor enables users to perform similarity searches between a user input and a vector database. In the output, the "Divider" is meant to indicate the page number(s) the text chunk is on. The issue here is that, for .docx files, the "Divider" is equal to 1 for all text chunks.

#### How to reproduce the issue

1. Go to https://workshop.cfg.deloitte.com/cfg-ai-dev/SemossWeb/packages/client/dist/#/
2. Create a vector database (I used FAISS) and upload a .docx file.
4. Go to the vector db and click on the Q&A tab
5. With the network calls open, ask a question and click "Generate Answer"
6. Go to the response of the VectorDatabaseQuery call

### Expected results
The "Divider" value should represent the page at which that text exists in the document

### Actual results
The "Divider" value is 1 for all chunks

#### Screenshots

Image

### Environment
- browser type and version: Google Chrome v135.0.7049.96
- node.js version: v18.20.3

### PR DESCRIPTION
**Pull request by Varaham**
# Description :
The VectorDatabaseQueryReactor enables users to perform similarity searches between a user input and a vector database.
The "output" JSON value in the "pixelReturn" Response JSON contains the "Divider" as the attribute which is meant to indicate the page number(s) the text chunk is on.

### Current issue:
In the current output ,for .docx files, the "Divider" is equal to 1 for all text chunks irrespective of the page number at which the text exists / spanned in the document.

### Workaround implementation :
Below are the steps in workaround implementation -

The docx contents are divided into individual paragraphs as separate chunks using XWPF API POI class.
When the page break is encountered, the page count is incremented and the Divider will have the page number at which the text chunk (paragraph) exists.

### Exceptions :
The page break will be ignored in the below scenarios:

Whenever any image has been spanned in between the pages.
Whenever any tabular fields are spanned in between the pages
Any JSON values are spanned in between the pages.
In the above scenario, the DocReader will take the entire value as a single text chunk (paragraph) and will take the last page till the objects are spanned. The Divider will take all the page numbers with comma separated values and will be displayed in the JSON output.

### Steps :
Click on 'Open Vector' and create a new Vector Catalog database with all the required fields.
In the Vector Catalog window, go to the 'Files' tab to upload a new docx file. (pic 1)
In the Files tab, click on 'Embed new Document' button (pic 2)
Select any docx file (pic 3)
Click on 'Embed' and ensure that it is embedded (pic 4)
Once the document is uploaded , listed (pic 5)
Go to the 'Q & A' tab. Type a question and click on ' Generate Answer'. See in the response JSON in the 'Networks tab'.

image
image
image
image
image
image
[Response JSON.txt](https://github.com/user-attachments/files/20185285/Response.JSON.txt)

### CODE REVIEW

**Comment by ppatel9703** [comment]
Can we add in a proper description and testing steps.

File: src/prerna/reactor/frame/gaas/processors/DocProcessor.java [hunk 1]
```diff
@@ -104,20 +108,43 @@ private void processParagraphs(XWPFDocument document) {
 		int pageNo = 1;
 		String source = getSource(this.filePath);
 
-		for (XWPFParagraph paragraph : document.getParagraphs()) {
+		XWPFParagraph lastParaOnPage = null;
+		int pageCount = document.getProperties().getExtendedProperties().getUnderlyingProperties().getPages();
+	    System.out.println(" pageCount -> " + pageCount);
```
Comment (ppatel9703) [inline src/prerna/reactor/frame/gaas/processors/DocProcessor.java]: Pls Remove the sysout

**Comment by Varaham** [comment]
Console Output replaced with Loggers as per review comments

File: src/prerna/reactor/frame/gaas/processors/DocProcessor.java (hunk 1 above)
Comment (Varaham) [reply src/prerna/reactor/frame/gaas/processors/DocProcessor.java]: code committed after replacing sysout with loggers

**Review by ppatel9703 — APPROVED** [review]
